### ISSUE TITLE
Reorder some things

### ISSUE THREAD

**Issue by fernandosoto138** [XD-DENG/SQL-exercise#8]
I saw this repo and it's great how much exercises are. 

It would be great what the exercises are separated from solutions.

If you accept pull request, I offer myself to do that work.

**Comment by XD-DENG** [comment]
Thanks @fernandosoto138 for offering this!

I agree with you that it may be good to have quiz separated from solutions. At this moment what we have is them together in a file named as `*_questions_and_solutions.sql`. Possibly what you can help is to have another file `*_questions.txt` in which we have pure quiz (I think we can still keep the quiz in the file `*_questions_and_solutions.sql` so that it's more convenient when people cross-check afterwards).

For sure I would accept PR. May you help do the changes you're proposing for one exercise set first, say [SQL_exercise_01/](https://github.com/XD-DENG/SQL-exercise/tree/master/SQL_exercise_01), and let's discuss what is the best way, before you help do this for all the exercises (to avoid wasting your time). Does this work for you?

Thanks again!

**Comment by XD-DENG** [comment]
Will address with PR #9
